version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pgsql_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: python_learning_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  ubuntu:
    build: .
    container_name: ubuntu_22_04
    ports:
      - "2222:22"
    volumes:
      - ./:/workspace
    tty: true
    stdin_open: true
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: python_db
      MYSQL_USER: python_user
      MYSQL_PASSWORD: python_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  postgres_data:
    name: python_learning_postgres_data
  mysql_data:
    name: python_learning_mysql_data 